apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-api-pipelines
parameters:
- description: Defines the location of the estafet github (change this if you have forked and want to use another github)
  name: GITHUB
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: build-project-api
    name: build-project-api
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-microservices-scrum-api-project"
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: GITHUB
            value: ${GITHUB}
        jenkinsfilePath: openshift/pipelines/build-pipeline.groovy
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pipeline
      name: release-project-api
    name: release-project-api
  spec:
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "https://github.com/${GITHUB}/estafet-microservices-scrum-api-project"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/pipelines/release-pipeline.groovy
      type: JenkinsPipeline
  status:
    lastVersion: 0    